version: '3.9'

networks:
  application:

volumes:
  - metall-db

services:
  server:
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    container_name: server
    build:
      context: ./
      dockerfile:  ./Dockerfile
    environment:
      POSTGRES_PASSWORD: very_difficult_postgress_password
      POSTGRES_USER: service_user
      POSTGRES_DB:  service_db
      POSTGRES_HOST: postgresdb
      POSTGRES_PORT: 5432
    command: "gunicorn   --bind 0.0.0.0:80 metall.wsgi"
    volumes:
      - "./media:/app/media"
    networks:
          - application

  db:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: very_difficult_postgress_password
      POSTGRES_USER: service_user
      POSTGRES_DB: service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U service_user -d service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - metall-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
          - application

  proxy:
        image: nginx:1.23-alpine
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./media:/media
        depends_on:
            - db
            - server
            - pgadmin
        networks:
            - application
    