# Generated by Django 4.1.7 on 2023-03-21 18:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', wagtail.fields.StreamField([('footer', wagtail.blocks.StructBlock([('about_us_title', wagtail.blocks.CharBlock(help_text='Заголовок о нас', required=True)), ('about_us_text', wagtail.blocks.RichTextBlock(help_text='Текст о нас', required=True)), ('work_time_title', wagtail.blocks.CharBlock(help_text='Заголовок график работы', required=True)), ('work_time_text', wagtail.blocks.RichTextBlock(help_text='Текст график работы', required=True)), ('services_title', wagtail.blocks.CharBlock(help_text='Заголовок услуги', required=True)), ('services_text', wagtail.blocks.RichTextBlock(help_text='Текст услуги', required=True))]))], use_json_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(help_text='Добавить логотип', required=False)), ('call_us_text', wagtail.blocks.CharBlock(help_text='Текст с призывом позвонить', required=True)), ('call_us_number', wagtail.blocks.CharBlock(help_text='Номер телефона', required=True)), ('email_text', wagtail.blocks.CharBlock(help_text='Текст c призывом написать email', required=True)), ('email_address', wagtail.blocks.CharBlock(help_text='Email адрес', required=True)), ('address_text', wagtail.blocks.CharBlock(help_text='Текст с призывом приехать', required=True)), ('address', wagtail.blocks.CharBlock(help_text='Адрес', required=True)), ('apply_button_text', wagtail.blocks.CharBlock(help_text='Кнопка заявки', required=True)), ('apply_button_url', wagtail.blocks.URLBlock(help_text='Ссылка кнопки', required=True))]))], use_json_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', wagtail.fields.StreamField([('menus', wagtail.blocks.StructBlock([('title_menu', wagtail.blocks.CharBlock(help_text='Название меню', required=True)), ('title_url', wagtail.blocks.URLBlock(help_text='Ссылка на страницу', required=True))]))], use_json_field=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('metall', wagtail.fields.StreamField([('metall', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Заголовок', required=True)), ('text', wagtail.blocks.RichTextBlock(help_text='Текст', required=True))]))], blank=True, null=True, use_json_field=None)),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.footer')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.header')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.menu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
