# Generated by Django 4.1.7 on 2023-03-16 21:35

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu",
                    wagtail.fields.StreamField(
                        [
                            (
                                "menus",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title_menu",
                                            wagtail.blocks.CharBlock(
                                                help_text="Add your title",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "title_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="Add additional text",
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=None,
                    ),
                ),
            ],
        ),
    ]
