# Generated by Django 4.1.7 on 2023-03-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.menu",
            ),
        ),
    ]
