# Generated by Django 4.1.7 on 2023-03-18 19:11

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    wagtail.fields.StreamField(
                        [
                            (
                                "header",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "logo",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Добавить логотип",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "call_us_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Текст с призывом позвонить",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "call_us_number",
                                            wagtail.blocks.CharBlock(
                                                help_text="Номер телефона",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "email_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Текст c призывом написать email",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "email_address",
                                            wagtail.blocks.CharBlock(
                                                help_text="Email адрес", required=True
                                            ),
                                        ),
                                        (
                                            "address_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Текст с призывом приехать",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "address",
                                            wagtail.blocks.CharBlock(
                                                help_text="Адрес", required=True
                                            ),
                                        ),
                                        (
                                            "apply_button_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Кнопка заявки", required=True
                                            ),
                                        ),
                                        (
                                            "apply_button_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="Ссылка кнопки", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="menu",
            name="menu",
            field=wagtail.fields.StreamField(
                [
                    (
                        "menus",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title_menu",
                                    wagtail.blocks.CharBlock(
                                        help_text="Название меню", required=True
                                    ),
                                ),
                                (
                                    "title_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Ссылка на страницу", required=True
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
