# Generated by Django 4.1.7 on 2023-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_header"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [
                            (
                                "footer",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "about_us_title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Заголовок о нас",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "about_us_text",
                                            wagtail.blocks.RichTextBlock(
                                                help_text="Текст о нас", required=True
                                            ),
                                        ),
                                        (
                                            "work_time_title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Заголовок график работы",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "work_time_text",
                                            wagtail.blocks.RichTextBlock(
                                                help_text="Текст график работы",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "services_title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Заголовок услуги",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "services_text",
                                            wagtail.blocks.RichTextBlock(
                                                help_text="Текст услуги", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.footer",
            ),
        ),
    ]
