# Generated by Django 4.1.7 on 2023-03-20 13:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_footer_homepage_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="metall",
            field=wagtail.fields.StreamField(
                [
                    (
                        "metall",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Заголовок", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Текст", required=True
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
    ]
